<?php

        $apiKey="rzp_test_JgNvtia8jn6Hna";

        include 'db.php';

        session_start();

        

        $cusamount=$_GET['pr'];
        $bookqty=$_GET['qty'];
        $logidd=$_GET['l_id'];
        $cusorid=$_GET['o_id'];

       

       

        $query="SELECT * from `user` WHERE Login_id='$logidd'";

        $result=mysqli_query($conn,$query);

        while ($row = mysqli_fetch_assoc($result)) {

            $address=$row['Address'];

            $email=$row['Email'];

            $name=$row['Name'];

        }

 

        //$totalamount=$amount + $cusamount;

       

?>

<form action="razorpay.php?bid=<?php echo $cusorid ?>&&ld=<?php echo $logidd ?>&&am=<?php echo $cusamount?>" method="POST">

<script

    src="https://checkout.razorpay.com/v1/checkout.js"

    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys

    data-amount="<?php echo $cusamount * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.

    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account

    data-order_id="<?php rand(100000, 999999);?>"// Replace with the order_id generated by you in the backend.

    data-buttontext="Pay"

    data-name="BARELL OF BOOKS"//project name

    data-description="Best Place To Fresh Your MIND and HEART "

    

    

    data-theme.color="#F37254"

></script>

<input type="hidden" custom="Hidden Element" name="hidden">

</form>

 

<!--style>

.razorpay-payment-button { display:none; }

</style>

 

<script type="text/javascript">

  $(document).ready(function(){

    $('.razorpay-payment-button').click();

 

});

</script-->